plugins {
    id 'java'
}

group = 'com.pinnacle'
version = '1.4'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:26.2.build.+"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
